const allProduct = [
    {
        name: 'Ash Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '3',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Ash Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '60',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Brown Hardwood Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '100',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '199',
        salePrice: '250',
        discount: '13',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '0',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
    {
        name: 'Deluxe Mahagony Double Bed',
        description: 'A bed is a piece of furniture which is used as a place to sleep or relax.',
        img: 'https://s3.amazonaws.com/redqteam.com/pickbazar/furniture/Ash.png',
        price: '250',
        salePrice: '250',
        discount: '10',
        quantity: '1',
        type: 'Bed',
        categories: 'Master Bad'
    },
]

export default allProduct;